version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "neo-werewolf-backend-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m81n0hmef4hy"
s3_prefix = "neo-werewolf-backend-test"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
